version: '3'
services:
  app:
    build:
      context: .
      target: builder
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    command: /app/scripts/run-dev.sh
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongodb_data:
